export const posts = [
  {
    id: 32,
    postvideo: "",
    postimage: "post.png",
    avatar: "user.png",
    user: "Surfiya Zakir",
    time: "22 min ago",
    like: 760,
    comment: 0,
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nulla dolor, ornare at commodo non, feugiat non nisi. Phasellus faucibus mollis pharetra. Proin blandit ac massa sed rhoncus.",
  },
  {
    id: 33,
    postvideo: "",
    postimage: "post.png",
    avatar: "user.png",
    user: "Surfiya Zakir",
    time: "22 min ago",
    like: 760,
    comment: 0,
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nulla dolor, ornare at commodo non, feugiat non nisi. Phasellus faucibus mollis pharetra. Proin blandit ac massa sed rhoncus.",
  },
  {
    id: 34,
    postvideo: "",
    postimage: "post.png",
    avatar: "user.png",
    user: "Surfiya Zakir",
    time: "22 min ago",
    like: 760,
    comment: 0,
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nulla dolor, ornare at commodo non, feugiat non nisi. Phasellus faucibus mollis pharetra. Proin blandit ac massa sed rhoncus.",
  },
  {
    id: 35,
    postvideo: "",
    postimage: "post.png",
    avatar: "user.png",
    user: "Surfiya Zakir",
    time: "22 min ago",
    like: 760,
    comment: 0,
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nulla dolor, ornare at commodo non, feugiat non nisi. Phasellus faucibus mollis pharetra. Proin blandit ac massa sed rhoncus.",
  },
  {
    id: 36,
    postvideo: "",
    postimage: "post.png",
    avatar: "user.png",
    user: "Surfiya Zakir",
    time: "22 min ago",
    like: 760,
    comment: 0,
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nulla dolor, ornare at commodo non, feugiat non nisi. Phasellus faucibus mollis pharetra. Proin blandit ac massa sed rhoncus.",
  },
  {
    id: 37,
    postvideo: "",
    postimage: "post.png",
    avatar: "user.png",
    user: "Surfiya Zakir",
    time: "22 min ago",
    like: 760,
    comment: 0,
    des: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nulla dolor, ornare at commodo non, feugiat non nisi. Phasellus faucibus mollis pharetra. Proin blandit ac massa sed rhoncus.",
  },
];
