export const dataLicenseProfile = [
  {
    id_credential: 89328892,
    license_name: "Professional Broker License",
    license_logo: "/assets/images/profile/image 15.png",
    license_granted_date: "10-2022",
    license_expiry_date: null,
    issuing_organization: "VNDirect",
  },
  {
    id_credential: 89328893,
    license_name: "Professional Broker License",
    license_logo: "/assets/images/profile/image 15.png",
    license_granted_date: "10-2022",
    license_expiry_date: null,
    issuing_organization: "VNDirect",
  },
  {
    id_credential: 89328894,
    license_name: "Professional Broker License",
    license_logo: "/assets/images/profile/image 15.png",
    license_granted_date: "10-2022",
    license_expiry_date: null,
    issuing_organization: "VNDirect",
  },
];
export const dataEducationProfile = [
  {
    id: 1,
    school_name: "MIT Sloan School of Management",
    degree: "MBA, Entrepreneurship & Innovation",
    activities: "Legatum Fellow, MIT 100K Business Plan Competition",
    start_year: 2009,
    end_year: 2011,
    school_logo: "/assets/images/profile/1631325873804.png",
  },
  {
    id: 1,
    school_name: "MIT Sloan School of Management",
    degree: "MBA, Entrepreneurship & Innovation",
    activities: "Legatum Fellow, MIT 100K Business Plan Competition",
    start_year: 2009,
    end_year: 2011,
    school_logo: "/assets/images/profile/1631325873804.png",
  },
  {
    id: 1,
    school_name: "MIT Sloan School of Management",
    degree: "MBA, Entrepreneurship & Innovation",
    activities: "Legatum Fellow, MIT 100K Business Plan Competition",
    start_year: 2009,
    end_year: 2011,
    school_logo: "/assets/images/profile/1631325873804.png",
  },
];
export const dataExperiencesProfile = [
  {
    id: 1,
    company_name: "Experience Investor",
    industry: "Binance",
    company_logo: "/assets/images/profile/alabaster_global_logo.png",
    start_date: "2019-01-20",
    end_date: "2024-08-20",
    location: "Vietnam",
    employment_type: "Full-time",
    description:
      "Building and leading operations in Vietnam to support the development of breakthrough software that can automatically analyze a wide range of medical images and provide physicians with real-time decision",
  },
  {
    id: 1,
    company_name: "Experience Investor",
    industry: "Binance",
    company_logo: "/assets/images/profile/alabaster_global_logo.png",
    start_date: "2019-01-20",
    end_date: "2024-08-20",
    location: "Vietnam",
    employment_type: "Full-time",
    description:
      "Building and leading operations in Vietnam to support the development of breakthrough software that can automatically analyze a wide range of medical images and provide physicians with real-time decision. Building and leading operations in Vietnam to support the development of breakthrough software that can automatically analyze a wide range of medical images and provide physicians with real-time decision",
  },
  {
    id: 1,
    company_name: "Experience Investor",
    industry: "Binance",
    company_logo: "/assets/images/profile/alabaster_global_logo.png",
    start_date: "2019-01-20",
    end_date: "2024-08-20",
    location: "Vietnam",
    employment_type: "Full-time",
    description:
      "Building and leading operations in Vietnam to support the development of breakthrough software that can automatically analyze a wide range of medical images and provide physicians with real-time decision",
  },
  {
    id: 1,
    company_name: "Experience Investor",
    industry: "Binance",
    company_logo: "/assets/images/profile/alabaster_global_logo.png",
    start_date: "2019-01-20",
    end_date: "2024-08-20",
    location: "Vietnam",
    employment_type: "Full-time",
    description:
      "Building and leading operations in Vietnam to support the development of breakthrough software that can automatically analyze a wide range of medical images and provide physicians with real-time decision",
  },
  {
    id: 1,
    company_name: "Experience Investor",
    industry: "Binance",
    company_logo: "/assets/images/profile/alabaster_global_logo.png",
    start_date: "2019-01-20",
    end_date: "2024-08-20",
    location: "Vietnam",
    employment_type: "Full-time",
    description:
      "Building and leading operations in Vietnam to support the development of breakthrough software that can automatically analyze a wide range of medical images and provide physicians with real-time decision",
  },
  {
    id: 1,
    company_name: "Experience Investor",
    industry: "Binance",
    company_logo: "/assets/images/profile/alabaster_global_logo.png",
    start_date: "2019-01-20",
    end_date: "2024-08-20",
    location: "Vietnam",
    employment_type: "Full-time",
    description:
      "Building and leading operations in Vietnam to support the development of breakthrough software that can automatically analyze a wide range of medical images and provide physicians with real-time decision",
  },
  {
    id: 1,
    company_name: "Experience Investor",
    industry: "Binance",
    company_logo: "/assets/images/profile/alabaster_global_logo.png",
    start_date: "2019-01-20",
    end_date: "2024-08-20",
    location: "Vietnam",
    employment_type: "Full-time",
    description:
      "Building and leading operations in Vietnam to support the development of breakthrough software that can automatically analyze a wide range of medical images and provide physicians with real-time decision",
  },
];
